-- MySQL Script generated by MySQL Workbench
-- Wed 22 Feb 2017 09:53:25 AM CST
-- Model: DemeBot Model    Version: 1.2
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DEMEBOT_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DEMEBOT_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DEMEBOT_DB` DEFAULT CHARACTER SET utf8 ;
USE `DEMEBOT_DB` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`TOOLS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`TOOLS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`BAYS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`BAYS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `r` FLOAT NOT NULL,
  `t` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `TOOL_id` INT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_BAYS_1_idx` (`TOOL_id` ASC),
  CONSTRAINT `fk_BAYS_1`
    FOREIGN KEY (`TOOL_id`)
    REFERENCES `DEMEBOT_DB`.`TOOLS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_TYPES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`PLANT_TYPES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `height` FLOAT NOT NULL,
  `width` FLOAT NOT NULL,
  `depth` FLOAT NOT NULL,
  `days_to_harvest` TINYINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLOT_POSITIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`PLOT_POSITIONS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `r` FLOAT NOT NULL,
  `t` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLOT_CONTENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`PLOT_CONTENTS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `planted_at` DATETIME NULL,
  `PLANT_TYPES_id` INT NULL,
  `PLOT_POSITIONS_id` INT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_PLOT_CONTENTS_1_idx` (`PLANT_TYPES_id` ASC),
  INDEX `fk_PLOT_CONTENTS_2_idx` (`PLOT_POSITIONS_id` ASC),
  CONSTRAINT `fk_PLOT_CONTENTS_1`
    FOREIGN KEY (`PLANT_TYPES_id`)
    REFERENCES `DEMEBOT_DB`.`PLANT_TYPES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLOT_CONTENTS_2`
    FOREIGN KEY (`PLOT_POSITIONS_id`)
    REFERENCES `DEMEBOT_DB`.`PLOT_POSITIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
