-- MySQL Script generated by MySQL Workbench
-- Fri 17 Feb 2017 04:22:31 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

USE `DEMEBOT_DB` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`TOOL_USE_LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`TOOL_USE_LOG` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`SYSTEM_ACTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`SYSTEM_ACTIONS` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_ACTION_LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`PLANT_ACTION_LOG` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_ACTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`PLANT_ACTIONS` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`ACTION_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`ACTION_TYPES` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_LIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`PLANT_LIST` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`BAY_LIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`BAY_LIST` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLOT_LIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`PLOT_LIST` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`TOOL_LIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`TOOL_LIST` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`PLANT_TYPES` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
