-- MySQL Script generated by MySQL Workbench
-- Wed 22 Feb 2017 09:53:25 AM CST
-- Model: DemeBot Model    Version: 1.2
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DEMEBOT_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`SEED_BINS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`SEED_BINS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `r` FLOAT NOT NULL,
  `t` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
