-- MySQL Script generated by MySQL Workbench
-- Fri 17 Feb 2017 04:22:31 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DEMEBOT_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DEMEBOT_DB` DEFAULT CHARACTER SET utf8 ;
USE `DEMEBOT_DB` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_TYPES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`PLANT_TYPES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `height` FLOAT UNSIGNED NOT NULL,
  `width` FLOAT UNSIGNED NOT NULL,
  `depth` FLOAT NOT NULL,
  `description` TEXT NULL,
  `days_to_germinate` TINYINT UNSIGNED NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Types of plants available to the system';

CREATE UNIQUE INDEX `PLANT_TYPES_id_UNIQUE` ON `DEMEBOT_DB`.`PLANT_TYPES` (`id` ASC);

CREATE UNIQUE INDEX `PLANT_TYPES_name_UNIQUE` ON `DEMEBOT_DB`.`PLANT_TYPES` (`name` ASC);


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`TOOL_LIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`TOOL_LIST` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'List of tools available to the system';

CREATE UNIQUE INDEX `TOOL_LIST_id_UNIQUE` ON `DEMEBOT_DB`.`TOOL_LIST` (`id` ASC);

CREATE UNIQUE INDEX `TOOL_LIST_name_UNIQUE` ON `DEMEBOT_DB`.`TOOL_LIST` (`name` ASC);


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLOT_LIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`PLOT_LIST` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `radius` FLOAT NOT NULL,
  `arc_angle` FLOAT NOT NULL,
  `description` TEXT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Describes the plot DemeBot is operating in.';

CREATE UNIQUE INDEX `PLOT_LIST_id_UNIQUE` ON `DEMEBOT_DB`.`PLOT_LIST` (`id` ASC);

CREATE UNIQUE INDEX `PLOT_LIST_name_UNIQUE` ON `DEMEBOT_DB`.`PLOT_LIST` (`name` ASC);


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`BAY_LIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`BAY_LIST` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `occupied_by_TOOL_LIST.id` INT NULL,
  `angle` FLOAT NULL COMMENT 'angle tools must enter and exit the bay.',
  `PLOT_LIST.id` INT NOT NULL,
  `delted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `occupied_by_TOOL_LIST.id`
    FOREIGN KEY (`occupied_by_TOOL_LIST.id`)
    REFERENCES `DEMEBOT_DB`.`TOOL_LIST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BAY_LIST_PLOT_LIST.id`
    FOREIGN KEY (`PLOT_LIST.id`)
    REFERENCES `DEMEBOT_DB`.`PLOT_LIST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'List of tool bays';

CREATE UNIQUE INDEX `BAY_LIST_id_UNIQUE` ON `DEMEBOT_DB`.`BAY_LIST` (`id` ASC);

CREATE INDEX `BAY_LIST_TRAY_INFO_idx` ON `DEMEBOT_DB`.`BAY_LIST` (`occupied_by_TOOL_LIST.id` ASC);

CREATE INDEX `BAY_LIST_BAY_INFO_idx` ON `DEMEBOT_DB`.`BAY_LIST` (`PLOT_LIST.id` ASC);


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_LIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`PLANT_LIST` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PLOT_LIST.id` INT NOT NULL,
  `PLANT_TYPES.id` INT NOT NULL,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `planted_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `PLANT_LIST_PLOT_LIST.id`
    FOREIGN KEY (`PLOT_LIST.id`)
    REFERENCES `DEMEBOT_DB`.`PLOT_LIST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PLANT_LIST_PLANT_TYPES.id`
    FOREIGN KEY (`PLANT_TYPES.id`)
    REFERENCES `DEMEBOT_DB`.`PLANT_TYPES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'List of individual plants. Each must have a location and a type';

CREATE UNIQUE INDEX `PLANT_LIST_id_UNIQUE` ON `DEMEBOT_DB`.`PLANT_LIST` (`id` ASC);

CREATE INDEX `PLANT_LIST_PLOT_INFO_idx` ON `DEMEBOT_DB`.`PLANT_LIST` (`PLOT_LIST.id` ASC);

CREATE INDEX `PLANT_LIST_PLANT_TYPE_idx` ON `DEMEBOT_DB`.`PLANT_LIST` (`PLANT_TYPES.id` ASC);


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`ACTION_TYPES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`ACTION_TYPES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL,
  `accepted_params` TEXT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deleted_at` DATETIME NULL,
  `TOOL_LIST.id` INT NULL,
  `duration` INT NULL COMMENT 'Tim in seconds action consumes.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Actions availabe to the system.';

CREATE UNIQUE INDEX `ACTION_TYPES_id_UNIQUE` ON `DEMEBOT_DB`.`ACTION_TYPES` (`id` ASC);


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_ACTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`PLANT_ACTIONS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PLANT_TYPES.id` INT NOT NULL,
  `ACTION_TYPES.id` INT NOT NULL,
  `delay_time` INT UNSIGNED NOT NULL,
  `required_count` SMALLINT NOT NULL,
  `frequency` INT UNSIGNED NOT NULL,
  `action_params` TEXT NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `PLANT_ACTIONS_PLANT_TYPES.id`
    FOREIGN KEY (`PLANT_TYPES.id`)
    REFERENCES `DEMEBOT_DB`.`PLANT_TYPES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PLANT_ACTIONS_ACTION_TYPES.id`
    FOREIGN KEY (`ACTION_TYPES.id`)
    REFERENCES `DEMEBOT_DB`.`ACTION_TYPES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'List of actions plants require on a routine basis';

CREATE UNIQUE INDEX `PLANT_ACTIONS_id_UNIQUE` ON `DEMEBOT_DB`.`PLANT_ACTIONS` (`id` ASC);

CREATE INDEX `PLANT_ACTIONS_PLANT_TYPES_idx` ON `DEMEBOT_DB`.`PLANT_ACTIONS` (`PLANT_TYPES.id` ASC);

CREATE INDEX `PLANT_ACTIONS_ACTION_TYPES_idx` ON `DEMEBOT_DB`.`PLANT_ACTIONS` (`ACTION_TYPES.id` ASC);


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_ACTION_LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`PLANT_ACTION_LOG` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PLANT_LIST.id` INT NOT NULL,
  `PLANT_ACTION_REQ.id` INT NOT NULL,
  `executed_at` DATETIME NOT NULL,
  `current_count` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `PLANT_ACTION_LOG_PLANT_ACTION_REQ.id`
    FOREIGN KEY (`PLANT_ACTION_REQ.id`)
    REFERENCES `DEMEBOT_DB`.`PLANT_ACTIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PLANT_ACTION_LOG_PLANT_LIST.id`
    FOREIGN KEY (`PLANT_LIST.id`)
    REFERENCES `DEMEBOT_DB`.`PLANT_LIST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Records log of maintainance actions performed on individual plants.';

CREATE UNIQUE INDEX `PLANT_ACTION_LOG_id_UNIQUE` ON `DEMEBOT_DB`.`PLANT_ACTION_LOG` (`id` ASC);

CREATE INDEX `PLANT_ACTION_LOG_PLANT_ACTION_REQ_idx` ON `DEMEBOT_DB`.`PLANT_ACTION_LOG` (`PLANT_ACTION_REQ.id` ASC);

CREATE INDEX `PLANT_ACTION_LOG_PLANT_LIST_idx` ON `DEMEBOT_DB`.`PLANT_ACTION_LOG` (`PLANT_LIST.id` ASC);


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`SYSTEM_ACTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`SYSTEM_ACTIONS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deleted_at` DATETIME NULL,
  `execute_at` DATETIME NOT NULL,
  `ACTION_TYPES.id` INT NOT NULL,
  `action_params` TEXT NULL,
  `description` TEXT NULL,
  `name` VARCHAR(45) NULL,
  `PLOT_LIST.id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `SYSTEM_ACTIONS_ACTION_TYPES.id`
    FOREIGN KEY (`ACTION_TYPES.id`)
    REFERENCES `DEMEBOT_DB`.`ACTION_TYPES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'List of system schedule actions.';

CREATE UNIQUE INDEX `SYSTEM_ACTIONS_id_UNIQUE` ON `DEMEBOT_DB`.`SYSTEM_ACTIONS` (`id` ASC);

CREATE INDEX `SYSTEM_ACTIONS_ACTION_TYPES_idx` ON `DEMEBOT_DB`.`SYSTEM_ACTIONS` (`ACTION_TYPES.id` ASC);


-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`TOOL_USE_LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEMEBOT_DB`.`TOOL_USE_LOG` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `log_entry` TEXT NOT NULL,
  `TOOL_LIST.id` INT NULL,
  `entered_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `TOOL_USE_LOG_TOOL_LIST.id`
    FOREIGN KEY (`TOOL_LIST.id`)
    REFERENCES `DEMEBOT_DB`.`TOOL_LIST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `TOOL_USE_LOG_id_UNIQUE` ON `DEMEBOT_DB`.`TOOL_USE_LOG` (`id` ASC);

CREATE INDEX `TOOL_USE_LOG_TOOL_LIST_idx` ON `DEMEBOT_DB`.`TOOL_USE_LOG` (`TOOL_LIST.id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
