-- MySQL Script generated by MySQL Workbench
-- Fri 17 Feb 2017 04:22:31 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

USE `DEMEBOT_DB` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLOT_CONTENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`PLOT_CONTENTS` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLOT_POSITIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`PLOT_POSITIONS` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`PLANT_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`PLANT_TYPES` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`BAYS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`BAYS` ;

-- -----------------------------------------------------
-- Table `DEMEBOT_DB`.`TOOLS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEMEBOT_DB`.`TOOLS` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
